### ISSUE TITLE
Error highlight call inputs which do match match task/subworkflow inputs

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/winstanley#83]

**Comment by aednichols** [comment]
This is a highly desirable feature according to @danxmoran on data gen

**Comment by aednichols** [comment]
I was able to get the actual inputs at a call site like this:
```
case callInput: WdlCallInput =>
      val actualInputs = callInput.psiElement.getChildren.filter {
        case _: WdlMapping => true
        case _ => false
      }
```
but in the limited time I tinkered with this, could not figure out how to compute the required inputs

**Comment by aednichols** [comment]
The following issues are related to making this feature everything it could be:
- Type checking https://github.com/broadinstitute/winstanley/issues/37
  - It would be nice to verify the types of the parameters in addition to the names
- Check calls to tasks that come from imports https://github.com/broadinstitute/winstanley/issues/63
  - Because we don't check that these tasks even exist now, we can't check that the inputs match
